name: CircleCI Simulation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build script
      run: |
        echo "Running build job"
        bash ./scripts/build.sh

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test script
      run: |
        echo "Running tests"
        bash ./scripts/test.sh
